version: '3'
services:
  flask:
    build:
        context: ./web
        dockerfile: Dockerfile
    container_name: flask_app
    ports:
     - "5000:5000"
  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    container_name: nginx
    ports:
        - "80:80"
